In [1]:
import numpy as np;

1.DataTypes & Attributes

In [ ]:
# Numpy's main datatype is an ndArray
a1 =  np.array([1,2,3])  # 1D Array
a1


array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [7]:
# 2D Array
a2 = np.array([
    [1,2,3],
    [4,5,6]
    ])
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:

# 3D Array
a3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
    ])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
# Shape
a1.shape

(3,)

In [16]:
# nDimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
# Data type 
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [17]:
# Size 
a1.size, a2.size, a3.size 

(3, 6, 18)

Create DataFrame from numpy Array

In [18]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

2. Creating Arrays

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [23]:
# ONES ARRAY 
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# RANGE ARRAY 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
# RANDOM ARRAY 
random_array = np.random.randint(0, 10, size=(3,5))
random_array, random_array.size, random_array.shape

(array([[6, 1, 4, 0, 8],
        [6, 1, 5, 0, 9],
        [5, 1, 3, 8, 4]]),
 15,
 (3, 5))

In [32]:
random_array_2 = np.random.random((5,3))
random_array_2, random_array_2.shape

(array([[0.87176081, 0.0993874 , 0.50131677],
        [0.318869  , 0.76794974, 0.57153516],
        [0.37429139, 0.5403401 , 0.88264487],
        [0.3563533 , 0.84062658, 0.16114898],
        [0.92408434, 0.73451819, 0.44660062]]),
 (5, 3))

In [33]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [34]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.76265609, 0.17170679, 0.66736918],
       [0.38989938, 0.65450926, 0.22378351],
       [0.49317874, 0.6400844 , 0.6003366 ],
       [0.87567097, 0.09255298, 0.75788322],
       [0.80250694, 0.69679531, 0.23886063]])

4.VIEW ARRAYS AND MATRICES

In [36]:
test_array = np.array([1,1,2,2,])
np.unique(test_array)

array([1, 2])

In [38]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]))

In [40]:
a1[0], a2[0], a3[0], a3[:2, :2, :2]


(1,
 array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[1, 2],
         [4, 5]],
 
        [[1, 2],
         [4, 5]]]))

5.MANIPULATING & COMPARING ARRAYS

In [ ]:
test_1 = [1,2,3] 
test_2 = np.ones(3)
test_1, test_2

([1, 2, 3], array([1., 1., 1.]))

In [ ]:
test_1 + test_2, test_1-test_2, test_1 * test_2, test_1/test_2, test_1//test_2  #//floor the value instead of nomral decimal in /

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]))

In [48]:
np.add(test_1,test_2), np.subtract(test_1,test_2), np.multiply(test_1,test_2), np.divide(test_1, test_2), np.exp(test_1), np.log(test_1)

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.        , 0.69314718, 1.09861229]))

5. AGGREGATION => Aggregation = performing the same operation on a number of things



In [50]:
listy_list = [1, 2, 3]
type(listy_list),sum(listy_list),sum(a1),np.sum(a1)

(list, 6, 6, 6)

In [51]:
massive_array = np.random.random(10000)
massive_array

array([0.68527727, 0.9041814 , 0.67664316, ..., 0.59136726, 0.82311972,
       0.1767656 ])

In [ ]:
%timeit sum(massive_array) #Python Sum
%timeit np.sum(massive_array) # Numpy Sum

# Use Numpy for optimizatons instead of normal python Sum

1.93 ms ± 304 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
21.7 μs ± 1.74 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [53]:
np.mean(massive_array), np.max(massive_array),np.min(massive_array)

(0.5014429596036475, 0.999929375095387, 9.007358091617235e-07)

Standard deviation and variance are measures of 'spread' of data.

The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard deviation and lower variance, the less spread out the values are.

# Standard deviation = a measure of how spread out a group of numbers is from the mean


In [54]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(massive_array)

0.28807001307290137

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(massive_array)

0.08298433243182156

In [56]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(massive_array))

0.28807001307290137

RESHAPING AND TRANSPOSE
array.reshape((1,2)) => change the dimensions
array.transpose() => change columns to rows, and rows to columns

In [58]:
a5 = np.array([1,2,3,4,5,6])
a2, a5

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [60]:
# a2 * a5
a5.shape, a2.shape

((6,), (2, 3))

In [69]:
a5_reshape = a5.reshape(2,3)
a5_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a5_reshape * a2


array([[ 1,  4,  9],
       [16, 25, 36]])

In [72]:
a2, a2.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

DOT PRODUCT: It will be useful when we want to multiply rows with column and columns with rows.... 

Note: Transpose will be useful here to convert rows into column and columns into rows

In [73]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [ ]:
mat1.shape, mat2.shape



((5, 3), (5, 3))

In [78]:
# Dot product => Error comes since here DOT product tries to mulitply 3rows with 5Columns whicgh are incompatable
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [79]:
mat3 = np.dot(mat1, mat2.T)
mat3


array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

COMPARISION OPERATORS

In [81]:
a1, a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [83]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

5. SORTING ARRAYS

In [84]:
random_array = np.random.randint(10, size=(3, 5))
random_array, np.sort(random_array), np.argsort(random_array)


(array([[2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7]]),
 array([[1, 2, 3, 3, 8],
        [0, 1, 3, 3, 7],
        [0, 4, 7, 9, 9]]),
 array([[3, 0, 1, 4, 2],
        [3, 4, 0, 1, 2],
        [2, 3, 4, 0, 1]], dtype=int64))

In [90]:
np.argmax(random_array, axis=0)


array([2, 2, 0, 2, 2], dtype=int64)

In [91]:
np.argmax(random_array, axis=1)


array([2, 2, 0], dtype=int64)

In [85]:
a1


array([1, 2, 3])

In [88]:
np.argsort(a1), np.argmin(a1)


(array([0, 1, 2], dtype=int64), 0)

In [89]:
np.argmax(a1)


2